kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
    - npm install
    - npm run build

- name: deploy-to-server
  image: drillster/drone-rsync
  settings:
    user:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    hosts:
      - jackharrhy.com
    source: ./build
    target:
      from_secret: target_dir
  when:
    branch:
      - master
    event:
      - push

- name: publish-to-docker
  image: plugins/docker
  settings:
    repo: jackharrhy/jackharrhy.com
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - push
      - tag
