pipeline:
  build:
    image: node
    commands:
      - npm install
      - npm run build

  publish:
    image: plugins/gh-pages
    settings:
      username: jackharrhy
      ssh_key:
        from_secret: ssh_key
      pages_directory: build/
    when:
      event: [ push, tag ]
      local: false

branches: master
when:
  event: [ push, pull_request, tag ]
