kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
    - npm install
    - npm run build

- name: publish-to-docker
  image: plugins/docker
  settings:
    repo: jackharrhy/jackharrhy.com
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      - master
    event:
      - push
      - tag
